plugins {
  id 'application'
  id 'org.openjfx.javafxplugin' version '0.1.0' //Plugin que ayuda a construir proyectos JAVAFX
}

repositories {
	mavenCentral()
}

javafx {
    version = "25"
    modules = [ 'javafx.base', 'javafx.swing', 'javafx.graphics', 'javafx.controls', 'javafx.fxml', 'javafx.media', 'javafx.web']
}

dependencies {
    implementation 'com.mysql:mysql-connector-j:8.0.33'
    implementation("org.controlsfx:controlsfx:11.2.2")
    
    // JasperReports - ACTUALIZAR a 7.0.3 para coincidir con JasperSoft Studio
    implementation 'net.sf.jasperreports:jasperreports:7.0.3'
    
    implementation 'org.apache.commons:commons-collections4:4.4'
    implementation 'commons-beanutils:commons-beanutils:1.9.4'
    implementation 'commons-digester:commons-digester:2.1'
    implementation 'commons-logging:commons-logging:1.2'
    implementation 'net.sf.jasperreports:jasperreports-pdf:7.0.3'
    implementation 'net.sf.jasperreports:jasperreports-fonts:7.0.3'
    implementation 'net.sf.jasperreports:jasperreports-javascript:7.0.3'
    implementation 'net.sf.jasperreports:jasperreports-charts:7.0.3'


}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

application {
    mainClass = 'com.javafx.ProyectoINT.InicioSesionMain'
}

sourceSets {
  main {
    resources {
        srcDirs = ["src/main/resources"]
        includes = ["**/*.fxml","**/*.png","**/*.properties","**/*.css","**/*.jasper","**/*.jrxml"]
    }
  }
}