plugins {
  id 'application'
  id 'org.openjfx.javafxplugin' version '0.1.0' //Plugin que ayuda a construir proyectos JAVAFX
}

repositories {
	mavenCentral()
}

javafx {
    version = "25"
    modules = [ 'javafx.base', 'javafx.swing', 'javafx.graphics', 'javafx.controls', 'javafx.fxml', 'javafx.media', 'javafx.web']
}

dependencies {
    implementation 'com.mysql:mysql-connector-j:8.0.33'
    implementation 'com.google.code.gson:gson:2.10.1'
    // https://mvnrepository.com/artifact/org.controlsfx/controlsfx
    implementation("org.controlsfx:controlsfx:11.2.2")
    implementation 'net.sf.jasperreports:jasperreports:7.0.1' 
    implementation 'net.sf.jasperreports:jasperreports-pdf:7.0.0' //Exportar PDF
    implementation 'net.sf.jasperreports:jasperreports-charts:7.0.1' //Charts
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

application {
    mainClass = 'com.javafx.ProyectoINT.InicioSesionMain'
}

sourceSets {
  main {
    resources {
        srcDirs = ["src/main/resources"]
        includes = ["**/*.fxml","**/*.png","**/*.properties","**/*.css","**/*.jasper","**/*.jrxml"]
    }
  }
}